'use client'

/**
 * The Approved-for-invoice tab — ONLY books someone has explicitly approved
 * for invoicing (Adnan, 2026-08-04). Two sections:
 *
 *   Awaiting invoice — approved, not yet raised. The action here is the one
 *   this tab exists for: "Mark invoice generated". Its totals row is the
 *   amount to be invoiced right now.
 *
 *   Invoice generated — the done pile, kept visible so the trail reads
 *   end-to-end. A mistaken mark can be undone.
 *
 * Rows carry the same billed numbers as the main table — same builder, same
 * arithmetic — so the two views cannot disagree about a book's value.
 */

import { useMemo, useState } from 'react'
import Link from 'next/link'
import type { Comic, Figure, Line, Program } from '@/types/content'
import {
  canApprove,
  markInvoiceGenerated,
  useApprovals,
  withdrawInvoiceMark,
} from '@/lib/approvals'
import { buildStatusTable, type StatusTableRow } from '@/lib/statusTable'
import { formatMoney, sumTaxes, type PricingConfig } from '@/lib/pricing'

const n = (v: number) => Math.round(v).toLocaleString('en-IN')

const TH =
  'whitespace-nowrap border-b border-brand-pale-dusk bg-white px-3 py-2.5 text-left font-sans text-[0.6rem] font-normal uppercase tracking-label text-brand-slate'
const TD =
  'whitespace-nowrap border-b border-brand-pale-dusk/50 px-3 py-2 align-middle font-sans text-[0.78rem] text-brand-indigo'

function InvoiceRows({
  rows, currency, canAct, busyKey, generated, onGenerate, onUndo,
}: {
  rows: StatusTableRow[]
  currency: string
  canAct: boolean
  busyKey: string | null
  generated: boolean
  onGenerate: (r: StatusTableRow) => void
  onUndo: (r: StatusTableRow) => void
}) {
  const totals = sumTaxes(rows)
  const pages = rows.reduce((s, r) => s + r.totalPages, 0)
  return (
    <div className="mt-3 overflow-x-auto rounded-xl border border-brand-pale-dusk bg-white">
      <table className="w-full min-w-[1180px] border-collapse">
        <thead>
          <tr>
            <th className={TH}>Classification</th>
            <th className={TH}>Comic</th>
            <th className={`${TH} text-right`}>Total pages</th>
            <th className={`${TH} text-right`}>Rate</th>
            <th className={`${TH} text-right`}>Invoice value</th>
            <th className={`${TH} text-right`}>With GST</th>
            <th className={`${TH} text-right`}>Net after TDS</th>
            <th className={TH}>Approved for invoice</th>
            <th className={TH}>{generated ? 'Invoice' : 'Action'}</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.key} className="hover:bg-brand-pale-dusk/20">
              <td className={TD}>{r.classification}</td>
              <td className={TD}>
                <Link
                  href={r.href}
                  className="underline decoration-brand-gold/60 underline-offset-2 hover:decoration-brand-gold"
                >
                  {r.title}
                </Link>
              </td>
              <td className={`${TD} text-right tabular-nums`} title={`${r.billed.interior} script + ${r.billed.extras} extras`}>
                {n(r.totalPages)}
              </td>
              <td className={`${TD} text-right tabular-nums`}>{formatMoney(r.rate, currency)}</td>
              <td className={`${TD} text-right font-semibold tabular-nums`}>{formatMoney(r.totalValue, currency)}</td>
              <td className={`${TD} text-right tabular-nums`} title={`GST 18% = ${formatMoney(r.gst, currency)}`}>
                {formatMoney(r.totalWithGst, currency)}
              </td>
              <td className={`${TD} text-right tabular-nums`} title={`TDS 2% = ${formatMoney(r.tds, currency)}`}>
                {formatMoney(r.netOfTds, currency)}
              </td>
              <td className={TD}>
                <span
                  className="font-sans text-[0.72rem] text-brand-slate"
                  title={`by ${r.invoice.approved?.by ?? ''}`}
                >
                  {r.invoice.approved?.at.slice(0, 10) ?? ''}
                </span>
              </td>
              <td className={TD}>
                {generated ? (
                  <span className="inline-flex items-center gap-1">
                    <span
                      className="rounded-full bg-brand-indigo px-2 py-0.5 font-sans text-[0.64rem] font-semibold text-white"
                      title={`Invoice generated by ${r.invoice.generated?.by ?? ''}`}
                    >
                      Invoiced {r.invoice.generated?.at.slice(0, 10)}
                    </span>
                    {canAct ? (
                      <button
                        type="button"
                        aria-label={`Undo invoice generated for ${r.title}`}
                        disabled={busyKey === r.key}
                        onClick={() => onUndo(r)}
                        title="Undo — the invoice was not actually raised"
                        className="rounded-full px-1 font-sans text-[0.72rem] text-brand-slate transition hover:text-brand-indigo disabled:opacity-40"
                      >
                        ×
                      </button>
                    ) : null}
                  </span>
                ) : canAct ? (
                  <button
                    type="button"
                    aria-label={`Mark invoice generated for ${r.title}`}
                    disabled={busyKey === r.key}
                    onClick={() => onGenerate(r)}
                    className="rounded-full border border-brand-indigo px-2.5 py-0.5 font-sans text-[0.6rem] uppercase tracking-label text-brand-indigo transition hover:bg-brand-indigo hover:text-white disabled:opacity-40"
                  >
                    Mark invoice generated
                  </button>
                ) : (
                  <span className="font-sans text-[0.72rem] text-brand-slate/50">Awaiting invoice</span>
                )}
              </td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr className="border-t-2 border-brand-pale-dusk bg-brand-pale-dusk/20">
            <td className={`${TD} font-semibold`} colSpan={2}>
              {generated ? 'Invoiced' : 'To invoice'} · {n(rows.length)} {rows.length === 1 ? 'book' : 'books'}
            </td>
            <td className={`${TD} text-right font-semibold tabular-nums`}>{n(pages)}</td>
            <td className={TD} />
            <td className={`${TD} text-right font-semibold tabular-nums`}>{formatMoney(totals.totalValue, currency)}</td>
            <td className={`${TD} text-right font-semibold tabular-nums`} title={`GST 18% = ${formatMoney(totals.gst, currency)}`}>
              {formatMoney(totals.totalWithGst, currency)}
            </td>
            <td className={`${TD} text-right font-semibold tabular-nums`} title={`TDS 2% = ${formatMoney(totals.tds, currency)}`}>
              {formatMoney(totals.netOfTds, currency)}
            </td>
            <td className={TD} colSpan={2} />
          </tr>
        </tfoot>
      </table>
    </div>
  )
}

export function InvoiceTable({
  comics,
  figures,
  lines,
  programs,
  pricing,
  email,
  canModerate,
  viewer = false,
  viewSwitcher,
}: {
  comics: Comic[]
  figures: Figure[] | null
  lines: Line[] | null
  programs: Program[] | null
  pricing: PricingConfig | null
  email: string | null
  canModerate: boolean
  /** Read-only role: sees the invoice trail, gets no buttons. */
  viewer?: boolean
  viewSwitcher?: React.ReactNode
}) {
  const [refreshKey, setRefreshKey] = useState(0)
  const [busyKey, setBusyKey] = useState<string | null>(null)
  const [note, setNote] = useState<string | null>(null)

  const approvals = useApprovals(refreshKey)
  const currency = pricing?.currency ?? 'INR'
  const canAct = canApprove(email, canModerate, viewer)

  const rows = useMemo(
    () =>
      buildStatusTable(
        comics, figures, lines, programs, pricing,
        approvals.data?.stages ?? null, approvals.data?.invoices ?? null,
      ).filter((r) => r.invoice.approved),
    [comics, figures, lines, programs, pricing, approvals.data],
  )

  const awaiting = rows.filter((r) => !r.invoice.generated)
  const done = rows.filter((r) => r.invoice.generated)

  async function act(key: string, fn: () => Promise<void>, okMsg: string) {
    setBusyKey(key)
    setNote(null)
    try {
      await fn()
      setRefreshKey((k) => k + 1)
      setNote(okMsg)
    } catch {
      setNote('Could not save — check that you are signed in with an approver account.')
    } finally {
      setBusyKey(null)
    }
  }

  return (
    <main className="mx-auto max-w-[1400px] px-6 pb-24 pt-10 md:pt-14">
      <header className="flex flex-wrap items-end justify-between gap-x-8 gap-y-4">
        <div>
          <span className="flex items-center gap-3">
            <span aria-hidden className="block h-px w-7 bg-brand-gold" />
            <span className="font-sans text-[0.7rem] uppercase tracking-label text-brand-gold">Studio status</span>
          </span>
          <h1 className="mt-3 font-serif font-light leading-tight text-brand-umber text-[2rem] md:text-[2.6rem]">
            Approved for invoice
          </h1>
          <p className="mt-2 max-w-2xl font-serif text-brand-umber/70 leading-relaxed">
            Only books that have been approved for invoicing appear here. When the invoice is actually
            raised, mark it generated — the mark is attributed and dated.
          </p>
        </div>
        <div className="flex items-center gap-2 pb-1">{viewSwitcher}</div>
      </header>

      {note ? (
        <p role="status" className="mt-4 font-sans text-[0.72rem] text-brand-indigo">{note}</p>
      ) : null}

      {rows.length === 0 ? (
        <p className="mt-8 rounded-xl border border-brand-pale-dusk bg-white px-4 py-10 text-center font-sans text-[0.8rem] text-brand-slate">
          Nothing is approved for invoice yet. Approve a book in the Invoice column of the table view
          and it will appear here.
        </p>
      ) : (
        <>
          <h2 className="mt-8 font-sans text-[0.7rem] uppercase tracking-label text-brand-slate">
            Awaiting invoice · {n(awaiting.length)}
          </h2>
          {awaiting.length ? (
            <InvoiceRows
              rows={awaiting}
              currency={currency}
              canAct={canAct}
              busyKey={busyKey}
              generated={false}
              onGenerate={(r) =>
                void act(r.key, () => markInvoiceGenerated(r.key, email ?? ''), `Invoice marked generated for ${r.title}.`)
              }
              onUndo={() => undefined}
            />
          ) : (
            <p className="mt-3 rounded-xl border border-brand-pale-dusk bg-white px-4 py-6 text-center font-sans text-[0.78rem] text-brand-slate">
              Every approved book has its invoice — nothing waiting.
            </p>
          )}

          {done.length ? (
            <>
              <h2 className="mt-10 font-sans text-[0.7rem] uppercase tracking-label text-brand-slate">
                Invoice generated · {n(done.length)}
              </h2>
              <InvoiceRows
                rows={done}
                currency={currency}
                canAct={canAct}
                busyKey={busyKey}
                generated
                onGenerate={() => undefined}
                onUndo={(r) =>
                  void act(
                    r.key,
                    () => withdrawInvoiceMark(r.key, 'generated', email ?? ''),
                    `Invoice-generated mark undone for ${r.title}.`,
                  )
                }
              />
            </>
          ) : null}
        </>
      )}

      <p className="mt-6 max-w-3xl font-sans text-[0.72rem] leading-relaxed text-brand-slate">
        Values are the same billed numbers as the table view — total pages × rate, GST 18% on the
        invoice value, TDS 2% of the invoice value only. The totals row under “Awaiting invoice” is
        the amount to raise right now.
      </p>
    </main>
  )
}
